version: '3'
#docker compose syntax version

services:
  #definition of my services (that will be containers)

  db:
    #    one service is db
    image: keinos/sqlite3:latest
    # an sqlite 3 image found on dockerhub
    container_name: sale-analysis-db
    volumes:
      - ./data:/workspace
    working_dir: /workspace
    # sets the default directory inside the container
    command: tail -f /dev/null
    # command that keeps the container running
  scripts:
    #   the other service is scripts
    build:
      context: .
      dockerfile: Dockerfile
      # instead of using an existing image, this service will be built from the Dockerfile
      # in the current directory
    container_name: scripts-exec
    volumes:
      - ./data:/app/data
      - ./dataviz:/app/dataviz
    depends_on:
      - db
      #specifies that this service needs the db service so db service will start first
    environment:
      - DB_PATH=/app/data/sale-analysis.db
      - DATA_PATH=/app/data
      - DATAVIZ_PATH=/app/dataviz
      - PYTHONPATH=/app
      # define app as a path where python will look for modules import